### ISSUE TITLE
Replacing Play Morphia 1.4.0 with 1.5.0a resulted in a CommandFailureException on start up

### ISSUE THREAD

**Issue by tazmaniax** [BlackLabs/play-morphia#126]
Any idea what this could be?

```
~ Server is up and running
11:56:32,115 [play-thread-1] INFO  ~ Loaded image cleaner plugin
11:56:32,135 [play-thread-1] DEBUG ~ MorphiaPlugin-1.5.0> reading configuration
11:56:32,774 [play-thread-1] INFO  ~ Connected to jdbc:h2:mem:play;MODE=MYSQL
11:56:34,185 [play-thread-1] DEBUG ~ MorphiaPlugin-1.5.0> mapping class: models.Campaign
11:56:34,354 [play-thread-1] ERROR ~ 

@6iohpdcm0
Internal Server Error (500) for request GET /

Oops: CommandFailureException
An unexpected error occured caused by exception CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "errmsg" : "Index with name: _created_-1 already exists with different options" , "code" : 85}

play.exceptions.UnexpectedException: Unexpected Error
    at play.Play.start(Play.java:567)
    at play.Play.detectChanges(Play.java:641)
    at play.Invoker$Invocation.init(Invoker.java:198)
    at Invocation.HTTP Request(Play!)
Caused by: com.mongodb.CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "errmsg" : "Index with name: _created_-1 already exists with different options" , "code" : 85}
    at com.mongodb.CommandResult.getException(CommandResult.java:76)
    at com.mongodb.CommandResult.throwOnError(CommandResult.java:131)
    at com.mongodb.DBCollectionImpl.createIndex(DBCollectionImpl.java:347)
    at com.mongodb.DBCollection.createIndex(DBCollection.java:564)
    at com.mongodb.DBCollection.ensureIndex(DBCollection.java:663)
    at org.mongodb.morphia.DatastoreImpl.ensureIndex(DatastoreImpl.java:314)
    at org.mongodb.morphia.DatastoreImpl.processEmbeddedAnnotations(DatastoreImpl.java:393)
    at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:372)
    at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:353)
    at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:348)
    at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:456)
    at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:449)
    at play.modules.morphia.MorphiaPlugin.configureDs_(MorphiaPlugin.java:826)
    at play.modules.morphia.MorphiaPlugin.onApplicationStart(MorphiaPlugin.java:697)
    at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:525)
    at play.Play.start(Play.java:537)
    ... 3 more
```

**Comment by karc** [comment]
So this is an old thread but I was actually running into the same issue upgrading to 1.5.0a.  I removed all of my old _created and _modified auto generated indexes and was able to get my app to startup and have them recreated.  However, I noticed that the indexes were actually recreated with the addition of expireAfterSeconds:0 as a property making these TTL indexes now.  I'm assuming that is where the real conflict is coming from.  Also it doesn't make sense for the auto generated created/modified dates to have a ttl on them of the date they were created or these documents would expire immediately.  It looks like the only reason they aren't expiring is because the date is saved as a Long vs an actual Date.  Is this the expected behavior?
